### PR TITLE
Fix GAFF AM1-BCC charging failures

### PR DESCRIPTION
**Pull request by jchodera**
This PR fixes charging failures that occur when some ligands are parameterized with the `GAFFTemplateGenerator`. 

cc: https://github.com/openforcefield/openforcefield/issues/492

### CODE REVIEW

**Comment by j-wags** [comment]
Does openmm-forcefields have the same philosophy as SMIRNOFF about generating its own input conformers for charge calculation? If so, then this should resolve the issue.

**Comment by jchodera** [comment]
> Does openmm-forcefields have the same philosophy as SMIRNOFF about generating its own input conformers for charge calculation? If so, then this should resolve the issue.

Yes, that's the idea---to attempt to use AM1-BCC ELF10 best practices (when available).

**Comment by hannahbrucemacdonald** [comment]
Please can I have permissions for this repo!

**Comment by jchodera** [comment]
@hannahbrucemacdonald : I'll let the tests run and merge in the morning!

**Comment by jchodera** [comment]
Hooray! Test pass!

**Pull request merged**
